spring:
  application:

  datasource:
    url: jdbc:mariadb://localhost:3307/first
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 테이블 자동 생성/업데이트
    show-sql: true  # SQL 로그 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true  # SQL 포매팅
logging:
  level:
    org.hibernate.SQL: DEBUG  # SQL 로그 레벨 설정
    org.hibernate.type.descriptor.sql: TRACE
